name: Prova CardTrader
on: workflow_dispatch
jobs:
  prova:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python prova.py
        env:
          CARDTRADER_TOKEN: ${{ secrets.CARDTRADER_TOKEN }}
